quiet: False
disable-version-string: True
with-expecter: True
mockname: "{{.InterfaceName}}"
filename: "{{.MockName}}.go"
packages:
  github.com/sitnikovik/sysmon/internal/metrics/cpu:
    config:
      recursive: True
      all: True
      dir: "{{.InterfaceDir}}"
      filename: "{{.InterfaceName}}_mock.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      inpackage: True
  github.com/sitnikovik/sysmon/internal/metrics/utils/cmd:
    config:
      recursive: True
      all: True
      dir: "{{.InterfaceDir}}"
      filename: "{{.InterfaceName}}_mock.go"
      mockname: "Mock{{.InterfaceName}}"
      outpkg: "{{.PackageName}}"
      inpackage: True
  