// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: api/sysmon.proto

package sysmon_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sysmon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_sysmon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_api_sysmon_proto_rawDescGZIP(), []int{0}
}

type StatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Represents the CPU statistics
	Cpu *StatsResponse_CPU `protobuf:"bytes,1,opt,name=cpu,proto3" json:"cpu,omitempty"`
	// Represents the disk statistics
	Disk *StatsResponse_Disk `protobuf:"bytes,2,opt,name=disk,proto3" json:"disk,omitempty"`
	// Represents the memory statistics
	Memory *StatsResponse_Memory `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	// Represents the system load average
	LoadAverage *StatsResponse_LoadAverage `protobuf:"bytes,4,opt,name=loadAverage,proto3" json:"loadAverage,omitempty"`
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sysmon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_sysmon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_api_sysmon_proto_rawDescGZIP(), []int{1}
}

func (x *StatsResponse) GetCpu() *StatsResponse_CPU {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *StatsResponse) GetDisk() *StatsResponse_Disk {
	if x != nil {
		return x.Disk
	}
	return nil
}

func (x *StatsResponse) GetMemory() *StatsResponse_Memory {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *StatsResponse) GetLoadAverage() *StatsResponse_LoadAverage {
	if x != nil {
		return x.LoadAverage
	}
	return nil
}

// Represents the CPU statistics
type StatsResponse_CPU struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Percentage of CPU time spent in user space
	User float64 `protobuf:"fixed64,1,opt,name=user,proto3" json:"user,omitempty"`
	// Percentage of CPU time spent in kernel space
	System float64 `protobuf:"fixed64,2,opt,name=system,proto3" json:"system,omitempty"`
	// Percentage of CPU time spent idle
	Idle float64 `protobuf:"fixed64,3,opt,name=idle,proto3" json:"idle,omitempty"`
}

func (x *StatsResponse_CPU) Reset() {
	*x = StatsResponse_CPU{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sysmon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsResponse_CPU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse_CPU) ProtoMessage() {}

func (x *StatsResponse_CPU) ProtoReflect() protoreflect.Message {
	mi := &file_api_sysmon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse_CPU.ProtoReflect.Descriptor instead.
func (*StatsResponse_CPU) Descriptor() ([]byte, []int) {
	return file_api_sysmon_proto_rawDescGZIP(), []int{1, 0}
}

func (x *StatsResponse_CPU) GetUser() float64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *StatsResponse_CPU) GetSystem() float64 {
	if x != nil {
		return x.System
	}
	return 0
}

func (x *StatsResponse_CPU) GetIdle() float64 {
	if x != nil {
		return x.Idle
	}
	return 0
}

// Represents the disk statistics
type StatsResponse_Disk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Number of reads per second
	Reads float64 `protobuf:"fixed64,1,opt,name=reads,proto3" json:"reads,omitempty"`
	// Number of writes per second
	Writes float64 `protobuf:"fixed64,2,opt,name=writes,proto3" json:"writes,omitempty"`
	// Number of kilobytes read+write per second
	ReadWriteKB float64 `protobuf:"fixed64,3,opt,name=readWriteKB,proto3" json:"readWriteKB,omitempty"`
	// Total disk space in MB
	TotalMB uint64 `protobuf:"varint,4,opt,name=totalMB,proto3" json:"totalMB,omitempty"`
	// Used disk space in MB
	UsedMB uint64 `protobuf:"varint,5,opt,name=usedMB,proto3" json:"usedMB,omitempty"`
	// Used disk space in percentage
	UsedPercent float64 `protobuf:"fixed64,6,opt,name=usedPercent,proto3" json:"usedPercent,omitempty"`
	// Number of used inodes
	UsedInodes uint64 `protobuf:"varint,7,opt,name=usedInodes,proto3" json:"usedInodes,omitempty"`
	// Used inodes in percentage
	UsedInodesPercent float64 `protobuf:"fixed64,8,opt,name=usedInodesPercent,proto3" json:"usedInodesPercent,omitempty"`
}

func (x *StatsResponse_Disk) Reset() {
	*x = StatsResponse_Disk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sysmon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsResponse_Disk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse_Disk) ProtoMessage() {}

func (x *StatsResponse_Disk) ProtoReflect() protoreflect.Message {
	mi := &file_api_sysmon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse_Disk.ProtoReflect.Descriptor instead.
func (*StatsResponse_Disk) Descriptor() ([]byte, []int) {
	return file_api_sysmon_proto_rawDescGZIP(), []int{1, 1}
}

func (x *StatsResponse_Disk) GetReads() float64 {
	if x != nil {
		return x.Reads
	}
	return 0
}

func (x *StatsResponse_Disk) GetWrites() float64 {
	if x != nil {
		return x.Writes
	}
	return 0
}

func (x *StatsResponse_Disk) GetReadWriteKB() float64 {
	if x != nil {
		return x.ReadWriteKB
	}
	return 0
}

func (x *StatsResponse_Disk) GetTotalMB() uint64 {
	if x != nil {
		return x.TotalMB
	}
	return 0
}

func (x *StatsResponse_Disk) GetUsedMB() uint64 {
	if x != nil {
		return x.UsedMB
	}
	return 0
}

func (x *StatsResponse_Disk) GetUsedPercent() float64 {
	if x != nil {
		return x.UsedPercent
	}
	return 0
}

func (x *StatsResponse_Disk) GetUsedInodes() uint64 {
	if x != nil {
		return x.UsedInodes
	}
	return 0
}

func (x *StatsResponse_Disk) GetUsedInodesPercent() float64 {
	if x != nil {
		return x.UsedInodesPercent
	}
	return 0
}

type StatsResponse_Memory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Total memory in MB
	TotalMB float64 `protobuf:"fixed64,1,opt,name=totalMB,proto3" json:"totalMB,omitempty"`
	// Available memory in MB shows how much memory in MB is available for new processes.
	AvailableMB float64 `protobuf:"fixed64,2,opt,name=availableMB,proto3" json:"availableMB,omitempty"`
	// Free memory in MB shows how much memory in MB is available for new processes.
	// If this value is high, it means that the system has some spare memory,
	// allowing more applications to run without having to free up memory.
	FreeMB float64 `protobuf:"fixed64,3,opt,name=freeMB,proto3" json:"freeMB,omitempty"`
	// Active memory in MB hows how much memory in MB that are currently being actively used by processes.
	// These pages contain data that is actively being read or written.
	ActiveMB float64 `protobuf:"fixed64,4,opt,name=activeMB,proto3" json:"activeMB,omitempty"`
	// Inactive shows how much memory in MB that were previously used but are not currently active.
	// These pages may contain data that is not used, but can be restored to the active state if necessary.
	InactiveMB float64 `protobuf:"fixed64,5,opt,name=inactiveMB,proto3" json:"inactiveMB,omitempty"`
	// Wired shows how much memory in MB  that are hard-locked in RAM and cannot be paged out or released.
	// These are usually mission-critical pages that are used by the operating system kernel or drivers,
	// and they are necessary for the system to work.
	WiredMB float64 `protobuf:"fixed64,6,opt,name=WiredMB,proto3" json:"WiredMB,omitempty"`
}

func (x *StatsResponse_Memory) Reset() {
	*x = StatsResponse_Memory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sysmon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsResponse_Memory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse_Memory) ProtoMessage() {}

func (x *StatsResponse_Memory) ProtoReflect() protoreflect.Message {
	mi := &file_api_sysmon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse_Memory.ProtoReflect.Descriptor instead.
func (*StatsResponse_Memory) Descriptor() ([]byte, []int) {
	return file_api_sysmon_proto_rawDescGZIP(), []int{1, 2}
}

func (x *StatsResponse_Memory) GetTotalMB() float64 {
	if x != nil {
		return x.TotalMB
	}
	return 0
}

func (x *StatsResponse_Memory) GetAvailableMB() float64 {
	if x != nil {
		return x.AvailableMB
	}
	return 0
}

func (x *StatsResponse_Memory) GetFreeMB() float64 {
	if x != nil {
		return x.FreeMB
	}
	return 0
}

func (x *StatsResponse_Memory) GetActiveMB() float64 {
	if x != nil {
		return x.ActiveMB
	}
	return 0
}

func (x *StatsResponse_Memory) GetInactiveMB() float64 {
	if x != nil {
		return x.InactiveMB
	}
	return 0
}

func (x *StatsResponse_Memory) GetWiredMB() float64 {
	if x != nil {
		return x.WiredMB
	}
	return 0
}

// Represents the system load average
type StatsResponse_LoadAverage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Average load for the last minute
	OneMin float64 `protobuf:"fixed64,1,opt,name=oneMin,proto3" json:"oneMin,omitempty"`
	// Average load for the last five minutes
	FiveMin float64 `protobuf:"fixed64,2,opt,name=fiveMin,proto3" json:"fiveMin,omitempty"`
	// Average load for the last fifteen minutes
	FifteenMin float64 `protobuf:"fixed64,3,opt,name=fifteenMin,proto3" json:"fifteenMin,omitempty"`
}

func (x *StatsResponse_LoadAverage) Reset() {
	*x = StatsResponse_LoadAverage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_sysmon_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatsResponse_LoadAverage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse_LoadAverage) ProtoMessage() {}

func (x *StatsResponse_LoadAverage) ProtoReflect() protoreflect.Message {
	mi := &file_api_sysmon_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse_LoadAverage.ProtoReflect.Descriptor instead.
func (*StatsResponse_LoadAverage) Descriptor() ([]byte, []int) {
	return file_api_sysmon_proto_rawDescGZIP(), []int{1, 3}
}

func (x *StatsResponse_LoadAverage) GetOneMin() float64 {
	if x != nil {
		return x.OneMin
	}
	return 0
}

func (x *StatsResponse_LoadAverage) GetFiveMin() float64 {
	if x != nil {
		return x.FiveMin
	}
	return 0
}

func (x *StatsResponse_LoadAverage) GetFifteenMin() float64 {
	if x != nil {
		return x.FifteenMin
	}
	return 0
}

var File_api_sysmon_proto protoreflect.FileDescriptor

var file_api_sysmon_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x79, 0x73, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x22, 0x0e, 0x0a, 0x0c, 0x53,
	0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xc3, 0x06, 0x0a, 0x0d,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a,
	0x03, 0x63, 0x70, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x6f, 0x6e,
	0x69, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x43, 0x50, 0x55, 0x52, 0x03, 0x63, 0x70, 0x75, 0x12, 0x2f, 0x0a, 0x04, 0x64,
	0x69, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x6f, 0x6e, 0x69,
	0x74, 0x6f, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x44, 0x69, 0x73, 0x6b, 0x52, 0x04, 0x64, 0x69, 0x73, 0x6b, 0x12, 0x35, 0x0a, 0x06,
	0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d,
	0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x06, 0x6d, 0x65, 0x6d,
	0x6f, 0x72, 0x79, 0x12, 0x44, 0x0a, 0x0b, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x65, 0x72, 0x61,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x6f, 0x6e, 0x69, 0x74,
	0x6f, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x52, 0x0b, 0x6c, 0x6f,
	0x61, 0x64, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x1a, 0x45, 0x0a, 0x03, 0x43, 0x50, 0x55,
	0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04,
	0x75, 0x73, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04,
	0x69, 0x64, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x69, 0x64, 0x6c, 0x65,
	0x1a, 0xf8, 0x01, 0x0a, 0x04, 0x44, 0x69, 0x73, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x77, 0x72, 0x69, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x06, 0x77, 0x72, 0x69, 0x74, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x72, 0x65, 0x61, 0x64, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x4b, 0x42, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x72, 0x65,
	0x61, 0x64, 0x57, 0x72, 0x69, 0x74, 0x65, 0x4b, 0x42, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x4d, 0x42, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x4d, 0x42, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x64, 0x4d, 0x42, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x64, 0x4d, 0x42, 0x12, 0x20, 0x0a, 0x0b, 0x75,
	0x73, 0x65, 0x64, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x0b, 0x75, 0x73, 0x65, 0x64, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x75, 0x73, 0x65, 0x64, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0a, 0x75, 0x73, 0x65, 0x64, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x2c, 0x0a,
	0x11, 0x75, 0x73, 0x65, 0x64, 0x49, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x50, 0x65, 0x72, 0x63, 0x65,
	0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x01, 0x52, 0x11, 0x75, 0x73, 0x65, 0x64, 0x49, 0x6e,
	0x6f, 0x64, 0x65, 0x73, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x1a, 0xb2, 0x01, 0x0a, 0x06,
	0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d,
	0x42, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x42,
	0x12, 0x20, 0x0a, 0x0b, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x4d, 0x42, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0b, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65,
	0x4d, 0x42, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x72, 0x65, 0x65, 0x4d, 0x42, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x06, 0x66, 0x72, 0x65, 0x65, 0x4d, 0x42, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x4d, 0x42, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x4d, 0x42, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x61, 0x63, 0x74, 0x69,
	0x76, 0x65, 0x4d, 0x42, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x69, 0x6e, 0x61, 0x63,
	0x74, 0x69, 0x76, 0x65, 0x4d, 0x42, 0x12, 0x18, 0x0a, 0x07, 0x57, 0x69, 0x72, 0x65, 0x64, 0x4d,
	0x42, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x57, 0x69, 0x72, 0x65, 0x64, 0x4d, 0x42,
	0x1a, 0x5f, 0x0a, 0x0b, 0x4c, 0x6f, 0x61, 0x64, 0x41, 0x76, 0x65, 0x72, 0x61, 0x67, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x6e, 0x65, 0x4d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x06, 0x6f, 0x6e, 0x65, 0x4d, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x69, 0x76, 0x65, 0x4d,
	0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x07, 0x66, 0x69, 0x76, 0x65, 0x4d, 0x69,
	0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x69, 0x66, 0x74, 0x65, 0x65, 0x6e, 0x4d, 0x69, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0a, 0x66, 0x69, 0x66, 0x74, 0x65, 0x65, 0x6e, 0x4d, 0x69,
	0x6e, 0x32, 0x4a, 0x0a, 0x0b, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x73,
	0x12, 0x3b, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x15, 0x2e, 0x6d,
	0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2f, 0x5a,
	0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x69, 0x74, 0x6e,
	0x69, 0x6b, 0x6f, 0x76, 0x69, 0x6b, 0x2f, 0x73, 0x79, 0x73, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x79, 0x73, 0x6d, 0x6f, 0x6e, 0x5f, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_sysmon_proto_rawDescOnce sync.Once
	file_api_sysmon_proto_rawDescData = file_api_sysmon_proto_rawDesc
)

func file_api_sysmon_proto_rawDescGZIP() []byte {
	file_api_sysmon_proto_rawDescOnce.Do(func() {
		file_api_sysmon_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_sysmon_proto_rawDescData)
	})
	return file_api_sysmon_proto_rawDescData
}

var file_api_sysmon_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_sysmon_proto_goTypes = []interface{}{
	(*StatsRequest)(nil),              // 0: monitor.StatsRequest
	(*StatsResponse)(nil),             // 1: monitor.StatsResponse
	(*StatsResponse_CPU)(nil),         // 2: monitor.StatsResponse.CPU
	(*StatsResponse_Disk)(nil),        // 3: monitor.StatsResponse.Disk
	(*StatsResponse_Memory)(nil),      // 4: monitor.StatsResponse.Memory
	(*StatsResponse_LoadAverage)(nil), // 5: monitor.StatsResponse.LoadAverage
}
var file_api_sysmon_proto_depIdxs = []int32{
	2, // 0: monitor.StatsResponse.cpu:type_name -> monitor.StatsResponse.CPU
	3, // 1: monitor.StatsResponse.disk:type_name -> monitor.StatsResponse.Disk
	4, // 2: monitor.StatsResponse.memory:type_name -> monitor.StatsResponse.Memory
	5, // 3: monitor.StatsResponse.loadAverage:type_name -> monitor.StatsResponse.LoadAverage
	0, // 4: monitor.SystemStats.GetStats:input_type -> monitor.StatsRequest
	1, // 5: monitor.SystemStats.GetStats:output_type -> monitor.StatsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_sysmon_proto_init() }
func file_api_sysmon_proto_init() {
	if File_api_sysmon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_sysmon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sysmon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sysmon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsResponse_CPU); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sysmon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsResponse_Disk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sysmon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsResponse_Memory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_sysmon_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatsResponse_LoadAverage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_sysmon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_sysmon_proto_goTypes,
		DependencyIndexes: file_api_sysmon_proto_depIdxs,
		MessageInfos:      file_api_sysmon_proto_msgTypes,
	}.Build()
	File_api_sysmon_proto = out.File
	file_api_sysmon_proto_rawDesc = nil
	file_api_sysmon_proto_goTypes = nil
	file_api_sysmon_proto_depIdxs = nil
}
