// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: api/sysmon.proto

package sysmon_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SystemStatsClient is the client API for SystemStats service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemStatsClient interface {
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type systemStatsClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemStatsClient(cc grpc.ClientConnInterface) SystemStatsClient {
	return &systemStatsClient{cc}
}

func (c *systemStatsClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, "/monitor.SystemStats/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemStatsServer is the server API for SystemStats service.
// All implementations must embed UnimplementedSystemStatsServer
// for forward compatibility
type SystemStatsServer interface {
	GetStats(context.Context, *StatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedSystemStatsServer()
}

// UnimplementedSystemStatsServer must be embedded to have forward compatible implementations.
type UnimplementedSystemStatsServer struct {
}

func (UnimplementedSystemStatsServer) GetStats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedSystemStatsServer) mustEmbedUnimplementedSystemStatsServer() {}

// UnsafeSystemStatsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemStatsServer will
// result in compilation errors.
type UnsafeSystemStatsServer interface {
	mustEmbedUnimplementedSystemStatsServer()
}

func RegisterSystemStatsServer(s grpc.ServiceRegistrar, srv SystemStatsServer) {
	s.RegisterService(&SystemStats_ServiceDesc, srv)
}

func _SystemStats_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemStatsServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/monitor.SystemStats/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemStatsServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemStats_ServiceDesc is the grpc.ServiceDesc for SystemStats service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemStats_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "monitor.SystemStats",
	HandlerType: (*SystemStatsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStats",
			Handler:    _SystemStats_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/sysmon.proto",
}
