# Dockerfile.ubuntu
FROM ubuntu:22.04

# Install necessary packages to monitor the system
RUN apt-get update && \
    apt-get install -y net-tools iproute2 lsof ca-certificates curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    ln -s /usr/bin/ss /usr/local/bin/netstat

# Install Go manually
RUN curl -OL https://golang.org/dl/go1.22.5.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.22.5.linux-amd64.tar.gz && \
    rm go1.22.5.linux-amd64.tar.gz && \
    ln -s /usr/local/go/bin/go /usr/bin/go

COPY . /app
WORKDIR /app
CMD ["go", "run", "./cmd/sysmon"]